# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI4_MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1117, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCells = QtWidgets.QMenu(self.menubar)
        self.menuCells.setObjectName("menuCells")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imv1 = ImageView(self.dockWidgetContents)
        self.imv1.setObjectName("imv1")
        self.horizontalLayout.addWidget(self.imv1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Text1 = QtWidgets.QSpinBox(self.dockWidgetContents_2)
        self.Text1.setMinimum(2)
        self.Text1.setMaximum(10)
        self.Text1.setObjectName("Text1")
        self.horizontalLayout_4.addWidget(self.Text1)
        self.Label1 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.Label1.setObjectName("Label1")
        self.horizontalLayout_4.addWidget(self.Label1)
        self.button1 = QtWidgets.QCheckBox(self.dockWidgetContents_2)
        self.button1.setObjectName("button1")
        self.horizontalLayout_4.addWidget(self.button1)
        self.button2 = QtWidgets.QCheckBox(self.dockWidgetContents_2)
        self.button2.setObjectName("button2")
        self.horizontalLayout_4.addWidget(self.button2)
        self.ResetButton = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.ResetButton.setObjectName("ResetButton")
        self.horizontalLayout_4.addWidget(self.ResetButton)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.GraficaSerieTiempo = PlotWidget(self.dockWidgetContents_3)
        self.GraficaSerieTiempo.setObjectName("GraficaSerieTiempo")
        self.horizontalLayout_2.addWidget(self.GraficaSerieTiempo)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_3)
        self.dockWidget_5 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_5.setObjectName("dockWidget_5")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Tabla = QtWidgets.QTableWidget(self.dockWidgetContents_5)
        self.Tabla.setObjectName("Tabla")
        self.Tabla.setColumnCount(0)
        self.Tabla.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.Tabla)
        self.dockWidget_5.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_5)
        self.openAction = QtWidgets.QAction(MainWindow)
        self.openAction.setObjectName("openAction")
        self.saveImgAction = QtWidgets.QAction(MainWindow)
        self.saveImgAction.setObjectName("saveImgAction")
        self.saveTimeSerAction = QtWidgets.QAction(MainWindow)
        self.saveTimeSerAction.setObjectName("saveTimeSerAction")
        self.findRoiAction = QtWidgets.QAction(MainWindow)
        self.findRoiAction.setObjectName("findRoiAction")
        self.LoadImageAction = QtWidgets.QAction(MainWindow)
        self.LoadImageAction.setObjectName("LoadImageAction")
        self.saveImgesAction = QtWidgets.QAction(MainWindow)
        self.saveImgesAction.setObjectName("saveImgesAction")
        self.menuFile.addAction(self.openAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.saveImgAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.LoadImageAction)
        self.menuFile.addAction(self.saveTimeSerAction)
        self.menuFile.addAction(self.saveImgesAction)
        self.menuCells.addAction(self.findRoiAction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCells.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCells.setTitle(_translate("MainWindow", "Cells"))
        self.Label1.setText(_translate("MainWindow", "Window Size"))
        self.button1.setText(_translate("MainWindow", "Show ROI\'s"))
        self.button2.setText(_translate("MainWindow", "Show Labels"))
        self.ResetButton.setText(_translate("MainWindow", "Reset"))
        self.openAction.setText(_translate("MainWindow", "Open Stack"))
        self.saveImgAction.setText(_translate("MainWindow", "Save Binary Image"))
        self.saveTimeSerAction.setText(_translate("MainWindow", "Save Time Series"))
        self.findRoiAction.setText(_translate("MainWindow", "Find Cells"))
        self.LoadImageAction.setText(_translate("MainWindow", "Load Binary Image"))
        self.saveImgesAction.setText(_translate("MainWindow", "Save Binary Images"))

from pyqtgraph import ImageView, PlotWidget
